// <auto-generated />
using System;
using FinanceTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceTracker.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("FinanceTracker.Models.ApplicationUser", b =>
        {
            b.Property<string>("Id").HasColumnType("TEXT");
            b.Property<int>("AccessFailedCount").HasColumnType("INTEGER");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<string>("DisplayName").HasColumnType("TEXT");
            b.Property<string>("Email").HasMaxLength(256).HasColumnType("TEXT");
            b.Property<bool>("EmailConfirmed").HasColumnType("INTEGER");
            b.Property<bool>("LockoutEnabled").HasColumnType("INTEGER");
            b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("TEXT");
            b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("TEXT");
            b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("TEXT");
            b.Property<string>("PasswordHash").HasColumnType("TEXT");
            b.Property<string>("PhoneNumber").HasColumnType("TEXT");
            b.Property<bool>("PhoneNumberConfirmed").HasColumnType("INTEGER");
            b.Property<string>("SecurityStamp").HasColumnType("TEXT");
            b.Property<bool>("TwoFactorEnabled").HasColumnType("INTEGER");
            b.Property<string>("UserName").HasMaxLength(256).HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
            b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
            b.ToTable("AspNetUsers", (string)null);
        });

        modelBuilder.Entity("FinanceTracker.Models.Transaction", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
            b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("Date").HasColumnType("TEXT");
            b.Property<string>("Notes").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<int>("Type").HasColumnType("INTEGER");
            b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("Date").HasDatabaseName("IX_Transactions_Date");
            b.HasIndex("UserId").HasDatabaseName("IX_Transactions_UserId");
            b.ToTable("Transactions");
        });

        modelBuilder.Entity("FinanceTracker.Models.Transaction", b =>
        {
            b.HasOne("FinanceTracker.Models.ApplicationUser", "User")
                .WithMany("Transactions")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("FinanceTracker.Models.ApplicationUser", b =>
        {
            b.Navigation("Transactions");
        });
#pragma warning restore 612, 618
    }
}
